[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
# new_contract = "GzxTdMYV51xQkJ5DTzWXij2kXZMibXWCg6JZJULEouXS"
spl_token = "A1DwTAisxvTXSAKDFQnvtY1uVXjLgiuw2pYqQF2pk3VH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
